local file = assert(io.open("Luagram/init.lua", "r"))
local content = file:read("*a")
file:close()
content = string.gsub(content, "local ([^ ]+) = require \"Luagram%.(.-)\"", function(modulename, filename)
  print(modulename, filename)
  local modulefile = assert(io.open("Luagram/" .. filename .. ".lua", "r"))
  local modulecontent = modulefile:read("*a")
  modulecontent = string.gsub(modulecontent, "([\r\f\n])([^\r\f\n])", "%1\t%2")
  modulefile:close()
  return string.format("----\n-- %s.lua\n----\nlocal %s = (function()\n\t%s\nend)()\n----", modulename, modulename, modulecontent)
end)
assert(io.open("Luagram.lua", "w")):write(content):close()