local file = assert(io.open("Luagram/init.lua", "r"))
local content = file:read("*a")
file:close()
content = string.gsub(content, "\nlocal ([a-zA-Z][a-zA-Z0-9_]*) = require \"Luagram%.(.-)\"\n", function(modulename, filename)
  local modulefile = assert(io.open("Luagram/" .. filename .. ".lua", "r"))
  local modulecontent = modulefile:read("*a")
  modulefile:close()
  return string.format("\n----\n-- %s.lua\n----\nlocal %s = (function()\n%s\nend)()\n----\n", modulename, modulename, modulecontent)
end)
assert(io.open("Luagram_build.lua", "w")):write(content):close()