name: redbean


on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Clone
        uses: actions/checkout@master
        with:
          repository: Propagram/Luagram
          path: Redbean

      - name: Download & Zip
        run: |
          curl https://redbean.dev/redbean-latest.com >redbean-lg.com
          mv Redbean .lua
          zip -r redbean-lg.com .lua/Luagram.lua

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: redbean-lg.com
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.tag }}
          draft: true