name: redbean


on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
      draft:
        required: true
        type: boolean

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Clone
        uses: actions/checkout@master
        with:
          repository: Propagram/Luagram
          path: Redbean

      - name: Download & Zip
        run: |
          curl https://redbean.dev/redbean-latest.com >redbean-lg.com
          rm -r Redbean/spec
          rm -r Redbean/docs
          rm -r Redbean/.git
          mv Redbean .lua
          zip -r redbean-lg.com .lua/Luagram.lua
          zip redbean-lg.zip redbean-lg.com

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: redbean-lg.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          name: redbean-luagram-${{ inputs.tag }}
          tag: ${{ inputs.tag }}
          draft: ${{ inputs.draft }}